char *words[12][50]={
	"area", "baby", "band", "bone", "chip", "crop", "desk", "door", "exit", "farm", "fish", "girl", "gold", "hair", "harm", "help", "jump", "jury", "kick", "king", "lock", "luck", "mail", "milk", "navy", "neck", "pair", "peak", "pipe", "rich", "sick", "size", "soft", "trip", "true", "tune", "unit", "wage", "walk", "warm", "wave", "well", "wife", "wild", "wind", "wise", "wish", "wood", "zero", "zone",
	"about", "adopt", "agent", "allow", "apply", "beach", "bloom", "brand", "built", "draft", "enjoy", "error", "faith", "flirt", "focus", "fresh", "grand", "guess", "guide", "happy", "hello", "human", "issue", "laugh", "light", "limit", "local", "match", "movie", "novel", "pound", "pride", "print", "proof", "queen", "rough", "royal", "rural", "shine", "sorry", "thank", "theft", "think", "title", "unity", "virus", "woman", "worry", "young", "youth", 
	"accept", "access", "belief", "bishop", "camera", "church", "coffee", "custom", "debate", "degree", "dinner", "effect", "engage", "ethnic", "fabric", "family", "famous", "female", "follow", "global", "ground", "health", "honest", "impact", "income", "junior", "labour", "lawyer", "league", "letter", "luxury", "market", "memory", "nation", "nature", "notice", "office", "online", "palace", "square", "strong", "switch", "valley", "vision", "visual", "volume", "wealth", "window", "writer", "yellow", 
	"ability", "absence", "academy", "account", "achieve", "acquire", "address", "advance", "airline", "alcohol", "already", "analyst", "ancient", "another", "anxiety", "anxious", "anybody", "arrange", "arrival", "assault", "attempt", "attract", "average", "backing", "balance", "banking", "barrier", "battery", "context", "control", "convert", "correct", "council", "country", "crucial", "crystal", "culture", "desktop", "dynamic", "journey", "summary", "suppose", "therapy", "uniform", "unknown", "unusual", "upgrade", "vehicle", "venture", "whether", 
	"absolute", "abstract", "academic", "accident", "attitude", "audience", "bachelor", "bacteria", "business", "capacity", "chairman", "champion", "children", "circular", "civilian", "computer", "conclude", "concrete", "conflict", "daughter", "deadline", "duration", "dynamics", "efficacy", "eighteen", "eligible", "engineer", "exercise", "explicit", "exposure", "facility", "festival", "football", "generous", "graphics", "heritage", "hospital", "industry", "keyboard", "magazine", "medicine", "positive", "possible", "practice", "precious", "question", "republic", "rigorous", "solution", "sympathy", 
	"Delicious", "adjective", "affection", "agitation", "alligator", "ambulance", "beautiful", "beginning", "boulevard", "brainless", "breathing", "challenge", "character", "chocolate", "confusion", "consonant", "curiosity", "different", "elocution", "everybody", "fireboard", "hamburger", "happiness", "imperfect", "important", "integrity", "invisible", "irregular", "knowledge", "marijuana", "nutrition", "packaging", "pineapple", "pollution", "president", "secretary", "september", "seventeen", "something", "sophomore", "structure", "vegetable", "withering", "wrestling", "xylophone", 
	"Antarctica", "absolution", "accelerate", "accountant", "adaptation", "appreciate", "atmosphere", "basketball", "blackboard", "compliment", "confidence", "conscience", "convection", "discipline", "earthquake", "excitement", "expression", "friendship", "generation", "government", "innovation", "insulation", "lightboard", "literature", "loneliness", "maleficent", "management", "motivation", "pilgrimage", "protection", "punishment", "reciprocal", "relaxation", "renovation", "resolution", "restaurant", "retirement", "salmonella", "silhouette", "strawberry", "technology", "television", "understand", "university", "volleyball", "watermelon", "wilderness", 
	"abiogenesis", "ablactation", "abomination", "achievement", "agriculture", "alternative", "androgynous", "anniversary", "application", "barbiturate", "belligerent", "caterpillar", "celebration", "certificate", "cheerleader", "cleanliness", "collocation", "communicate", "counterfeit", "defloration", "demarcation", "destination", "electricity", "environment", "evaporation", "everlasting", "excoriation", "exterminate", "forgiveness", "imagination", "information", "inspiration", "intelligent", "invigilator", "marshmallow", "nothingness", "photography", "preposition", "quadrillion", "quintillion", "rebarbative", "reservation", "responsible", "retribution", "screwdriver", "segregation", "serendipity", "subtraction", "syllabicate", "worldliness", 
	"acceleration", "acquaintance", "affectionate", "alliteration", "anticipation", "appreciation", "championship", "colonization", "commensalism", "compensation", "condensation", "degeneration", "grandparents", "independence", "intelligence", "interjection", "intermittent", "kaleidoscope", "perspiration", "preservation", "professional", "relationship", "supercilious", "supernatural", "trigonometry", 
	"International", "accommodation", "acetylcholine", "administrator", "advertisement", "anticlockwise", "antihistamine", "appropriation", "collaboration", "communication", "concentration", "confederation", "consciousness", "constellation", "consternation", "contemplating", "deforestation", "determination", "embarrassment", "encouragement", "enlightenment", "entertainment", "extraordinary", "factorization", "foregrounding", "globalisation", "indefatigable", "insignificant", "lackadaisical", "mathematician", "mitochondrion", "plasmodesmata", "pontification", "ratiocination", "reforestation", "regimentation", "reincarnation", "righteousness", "scarification", "skateboarding", "sportsmanship", "strangulation", "weightlifting", 
	"accommodations", "accomplishment", "accountability", "administration", "administrative", "anesthesiology", "antidepressant", "archaebacteria", "autosuggestion", "beautification", "biodegradation", "capitalization", "cardiovascular", "characteristic", "chemosynthesis", "chromatography", "communications", "defenestration", "electrophysics", "generalization", "identification", "initialisation", "interpretation", "multiplication", "nanotechnology", "neutralisation", "neutralization", "paleontologist", "pasteurization", "photosynthesis", "polymerization", "procrastinator", "reconciliation", "rehabilitation", "representation", "ridiculousness", "saponification", "simplification", "slaughterhouse", "specialization", "teleconference", "thermodynamics", "transformation", "transportation", "understandable", "understatement", "westernization", 
};
